[project]
name = "cartPole"
version = "0.1.0"
description = "Small project for OpenAI gymnasium cartPole using reinforcement learning methods"
module = "cartpole"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]
